### ISSUE TITLE
Update from 2020/1/4 fails on Firefox with endless waiting symbol

### ISSUE THREAD

**Issue by mzeilfelder** [AHgPuK/updatebookmark#1]
Since the plugin update from yesterday it no longer works on Firefox 71.0 (tested on Linux Debian and Windows 10). When clicking the Update Bookmark icon I now only get a popup dialog with a waiting icon (the turning circle).

Edit: I found out it only stopped working in private mode (which worked before). Without private mode it still works correct.

**Comment by mzeilfelder** [comment]
Works now. Thank you!

**Comment by ChrisMedley** [comment]
Still no update bookmark context menu in 1.4.7 yet version 1.4.5 works perfectly

**Comment by AHgPuK** [comment]
@ChrisMedley fixed in 1.4.8
Thanks for reporting
