### ISSUE TITLE
Unnecessary content script for Mozilla websites

### ISSUE THREAD

**Issue by PixievoltNo1** [AHgPuK/updatebookmark#10]
It seems that in the process of implementing #8, you left in a new content script that does nothing, but is set to run on all mozilla.org websites. Though the script is harmless, Firefox sees it as new access to mozilla.org being requested, blocks the automatic update, and informs users as such, bringing undue suspicion to the extension. The entire `content_scripts` key can be removed from manifest.json without impacting the extension's functionality.

**Comment by AHgPuK** [comment]
Fixed
