### ISSUE TITLE
Update URL context menu improviments

### ISSUE THREAD

**Issue by eliottmusk** [AHgPuK/updatebookmark#14]
Please make the Update URL context menu action much more specific and exact, for instance for the URL:

www.perfect-example.com/channels/dream-life/videos?o=vi&page=5

Just update bookmark that starts with "www.perfect-example.com/channels/dream-life/videos?o=vi&page="

so just the page number is different

Do not update an URL like:

www.perfect-example.com/channels/dream-life/videos?page=4

or

www.perfect-example.com/video/search?search=some+thing

Another example, if the bookmark is "https://another-example.com/video/search?search=one+thing&page=3"

do not update an URL like

"https://another-example.com/video/search?search=another+thing&page=8"

because one is "one+thing" and the other is "another-thing"

if the URL is "file:///C:/Users/Paul/Documents/New Docs/PP43X9.html"

do not update an bookmark like "file:///C:/Users/Paul/Documents/New/PP43X9.html"

I'm having many bookmarks that was wrong updated, my suggestion is, when using the Update URL context menu action just update without any popup if the URL is exact, just a different page number, if the URL is not exact then show the popup with the bookmarks to choose.

Thanks!

**Comment by AHgPuK** [comment]
All bookmarked candidates are sorted by close match. The best match should be the first place.
When you hover a cursor over a candidate it shows a tip what a bookmark url it is.
I don't want to disable an option to find all the bookmarks from the same domain.
Anyway, you can implement "strict similarity" functionality (also adding a checkbox to the options) and I will use your PR.

**Comment by eliottmusk** [comment]
Was just a feature request, thank you!

**Comment by AHgPuK** [comment]
Implemented in 1.9.0

**Comment by eliottmusk** [comment]
Thank you so much!
