### ISSUE TITLE
Feature Request: add option to horizontal scroll for pop-up menu.

### ISSUE THREAD

**Issue by aDreamEater** [AHgPuK/updatebookmark#15]
Very low priority, and strictly speaking not even necessary for this excellent add-on, but I would appreciate the ability to scroll to see the whole length of long bookmark titles in the update bookmark menu. 
Alternatively, include the full bookmark title in the mouseover tooltip above the existing mouseover tooltip URL.

**Comment by AHgPuK** [comment]
Resolved in 1.9.3
