### ISSUE TITLE
Updating bookmarks in a specific folder

### ISSUE THREAD

**Issue by el4ctr0n** [AHgPuK/updatebookmark#9]
Dear developers,

Can you please make it possible to load the current website titles of bookmarks in a specific folder?

Use case: When I import into the desktop Chrome the bookmarks I exported from Android Chrome (via this tool: https://android.stackexchange.com/questions/56635/how-can-i-export-the-list-of-open-chrome-tabs/199496#199496), the titles of the newly imported 
bookmarks are URLs, not the websites' titles.

I appreciate you considering my suggestion.
Thank you for your time.

**Comment by AHgPuK** [comment]
The extension works only for the currently opened tab and doesn't crawl any other sites.
